name: Mark last global release

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
    types:
      - closed

concurrency:
  group: mark-release
  cancel-in-progress: false

jobs:
  mark-release:
    if: ${{ startsWith(github.head_ref, 'release/') }} && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Mark global release
        run: |
          git config --local user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "GitHub Auto Release"
          echo "Marking last global release"
          git tag -fa "last-release" -m "Release last release global release"
          git push origin last-release --force --no-verify
          echo "Release last-release global marked"






